import Head from 'next/head';
import { useState } from 'react';
import { useMutation } from '@apollo/client';
import {
  CREATE_USER,
  UPDATE_USER,
  DELETE_USER,
} from '../crud-operations/queries';
import Container from '@mui/material/Container';
import EditModal from '../components/EditModal';
import ViewUsers from '../components/ViewData';
import CreateUser from '../components/CreateData';

const Home = () => {
  const [createUser] = useMutation(CREATE_USER, {
    onCompleted: (data) => {
      window.location.reload();
    },
  });

  const onSubmit = (e) => {
    e.preventDefault();
    createUser({
      variables: { name: e.target.name.value, email: e.target.name.value },
    });
  };

  const [deleteUser] = useMutation(DELETE_USER, {
    onCompleted: (data) => {
      window.location.reload();
    },
  });

  const onDelete = (id) => deleteUser({ variables: { id } });

  const [editId, setEditId] = useState('');

  const onClose = () => setEditId('');
  const openModal = (id) => setEditId(id);

  const [updateUser] = useMutation(UPDATE_USER, {
    onCompleted: () => setEditId(''),
  });

  const onSaveEdit = (e) => {
    e.preventDefault();
    updateUser({
      variables: {
        id: editId,
        name: e.target.name.value,
        email: e.target.email.value,
      },
    });
  };

  return (
    <Container maxWidth="xs">
      <Head>
        <title>
          CRUD APPLICATION WITH NEXTJS-GRAPHQL-MATERIAL UI-POSTGRESQL
        </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <EditModal isOpen={!!editId} onClose={onClose} onSubmit={onSaveEdit} />
      <CreateUser onSubmit={onSubmit} />
      <ViewUsers onDelete={onDelete} openModal={openModal} />
    </Container>

  );
}


export default Home;
